version: "3.8"

services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    restart: always
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong-migrations-up:
    image: kong:latest
    command: kong migrations up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:latest
    depends_on:
      - kong-database
      - kong-migrations
      - kong-migrations-up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net
    restart: always

  konga:
    image: pantsel/konga:latest
    depends_on:
      - kong
    environment:
      DB_ADAPTER: "postgres"
      DB_URI: "postgres://kong:kong@kong-database:5432/konga"
    ports:
      - "1337:1337"
    networks:
      - kong-net
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - kong-net
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
      - JWT_SECRET=639c18acf2dcc9c0da07
      - REDIS_HOST=redis
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  kong-db-data:
  redis-data:
