version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - kong-net
    volumes:
      - redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=2f5ae96c-b558-4c7b-a590-a501ae1c3f6c
      - JWT_SECRET=639c18acf2dcc9c0da07
      - REDIS_HOST=redis
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge

volumes:
  kong-db-data:
  redis-data:
