apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
